### PR TITLE
chore(identity-keys): use shared identity key store

### PR DESCRIPTION
**Pull request by Cali93**
### Context

Refactor chat-client to use `@walletconnect/identity-keys` for identity key related methods.
This PR will be merged once [the identity-keys package](https://github.com/WalletConnect/walletconnect-utils/pull/80)  is published

### CODE REVIEW

**Comment by bkrem** [comment]
@devceline I've adjusted the usage of the dedicated `IdentityKeys` class to map to how it's now functional in Push (shipped in `0.7.2`).

The one thing I'm still seeing in tests is due to the usage of `chatKeys`:

```
Error: No matching key. chat_identity_keys: eip155:1:0xbf05d71e6c7f91FaF723E5EE123839A1E336fEA6
 ❯ nt.getData ../../node_modules/@walletconnect/core/dist/index.cjs.js:1:39615
 ❯ nt.update ../../node_modules/@walletconnect/core/dist/index.cjs.js:1:38721
 ❯ ChatEngine.generateAndStoreInviteKey src/controllers/engine.ts:94:25
     92|     const pubKeyHex = await this.client.core.crypto.generateKeyPair();
     93|     const privKeyHex = this.client.core.crypto.keychain.get(pubKeyHex);
     94|     this.client.chatKeys.update(accountId, {
       |                         ^
     95|       inviteKeyPriv: privKeyHex,
     96|       inviteKeyPub: pubKeyHex,
```

i.e. we're now writing these keys to the shared `this.client.identityKeys` not `this.client.chatKeys`.

I'm not sure what you had in mind to address/refactor towards this so I'm not going to keep going solo here. Not high prio atm, but would be great if you could look into this at some point so we're then unblocked on Push + Chat in W3I 🙏

**Comment by bkrem** [comment]
Thanks for updating the chat-client for this @devceline 🙏 

Something I'd like to get clarity on: I'm seeing this unhandled rejection a lot when running the tests even when they pass (also on `main` so not related to this branch):

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: missing receiver public key
```

Do you know why?

**Comment by devceline** [comment]
> Thanks for updating the chat-client for this @devceline pray
> 
> Something I'd like to get clarity on: I'm seeing this unhandled rejection a lot when running the tests even when they pass (also on `main` so not related to this branch):
> 
> ```
> ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
> Error: missing receiver public key
> ```
> 
> Do you know why?

Yes, it's due to the fact symKeys are not being synced as of now, will be fixed when they are

**Comment by bkrem** [comment]
Are we good to merge here from your side too @devceline?

**Pull request merged**
